version: '3'
services:
  #diskover-web PHP Service
  app:
    image: php:7.4-fpm
    container_name: diskover-web-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: unless-stopped
  
  #Nginx Service
  web:
    image: nginx:1.21
    container_name: diskover-web-webserver
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8000:8000
    restart: unless-stopped
